# Generated by Django 6.0 on 2025-12-27 18:17

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Depense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_depense",
                    models.CharField(
                        choices=[
                            ("alimentation", "Alimentation"),
                            ("logement", "Logement"),
                            ("transport", "Transport"),
                            ("loisirs", "Loisirs"),
                            ("autre", "Autre"),
                        ],
                        max_length=50,
                    ),
                ),
                ("quartier", models.CharField(max_length=100)),
                (
                    "prix",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("lieu", models.CharField(max_length=200)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("commentaire", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="photos/"),
                ),
                ("anomalie", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
