# Generated by Django 6.0 on 2025-12-27 20:25

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="depense",
            options={
                "ordering": ["-date"],
                "verbose_name": "Dépense",
                "verbose_name_plural": "Dépenses",
            },
        ),
        migrations.AddField(
            model_name="depense",
            name="date_creation",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date de création",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="depense",
            name="date_modification",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de modification"
            ),
        ),
        migrations.AlterField(
            model_name="depense",
            name="anomalie",
            field=models.TextField(blank=True, verbose_name="Anomalie détectée"),
        ),
        migrations.AlterField(
            model_name="depense",
            name="commentaire",
            field=models.TextField(blank=True, verbose_name="Commentaire"),
        ),
        migrations.AlterField(
            model_name="depense",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Date"
            ),
        ),
        migrations.AlterField(
            model_name="depense",
            name="lieu",
            field=models.CharField(max_length=200, verbose_name="Lieu précis"),
        ),
        migrations.AlterField(
            model_name="depense",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="photos/",
                verbose_name="Photo justificative",
            ),
        ),
        migrations.AlterField(
            model_name="depense",
            name="prix",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="Prix (FCFA)",
            ),
        ),
        migrations.AlterField(
            model_name="depense",
            name="quartier",
            field=models.CharField(
                choices=[
                    ("campus", "Campus"),
                    ("centre_ville", "Centre-ville"),
                    ("quartier_1", "Quartier 1"),
                    ("quartier_2", "Quartier 2"),
                    ("quartier_3", "Quartier 3"),
                    ("autre", "Autre"),
                ],
                max_length=100,
                verbose_name="Quartier",
            ),
        ),
        migrations.AlterField(
            model_name="depense",
            name="type_depense",
            field=models.CharField(
                choices=[
                    ("alimentation", "Alimentation"),
                    ("logement", "Logement"),
                    ("transport", "Transport"),
                    ("loisirs", "Loisirs"),
                    ("autre", "Autre"),
                ],
                max_length=50,
                verbose_name="Type de dépense",
            ),
        ),
    ]
