# Generated by Django 4.2.27 on 2025-12-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_depense_options_depense_date_creation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depense",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
