# Generated by Django 4.2.27 on 2025-12-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_depense_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depense",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="depense",
            name="quartier",
            field=models.CharField(max_length=100, verbose_name="Quartier"),
        ),
    ]
